# Generated by Django 5.0.4 on 2024-04-19 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_description_alter_post_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(max_length=500, verbose_name='Краткое описание'),
        ),
    ]
